SET IDENTITY_INSERT [dbo].[StoreSection] ON
INSERT INTO [dbo].[StoreSection] ([StoreSectionID], [Name], [CoordinateX], [CoordinateY], [FloorPlanID]) VALUES (385, N'Bagværk', 726, 488, 1)
INSERT INTO [dbo].[StoreSection] ([StoreSectionID], [Name], [CoordinateX], [CoordinateY], [FloorPlanID]) VALUES (386, N'Chokolade', 559, 315, 1)
INSERT INTO [dbo].[StoreSection] ([StoreSectionID], [Name], [CoordinateX], [CoordinateY], [FloorPlanID]) VALUES (387, N'Marcipannsuch', 511, 314, 1)
INSERT INTO [dbo].[StoreSection] ([StoreSectionID], [Name], [CoordinateX], [CoordinateY], [FloorPlanID]) VALUES (388, N'Oste', 30, 348, 1)
INSERT INTO [dbo].[StoreSection] ([StoreSectionID], [Name], [CoordinateX], [CoordinateY], [FloorPlanID]) VALUES (389, N'Drikkelse', 27, 311, 1)
INSERT INTO [dbo].[StoreSection] ([StoreSectionID], [Name], [CoordinateX], [CoordinateY], [FloorPlanID]) VALUES (390, N'Pålæg', 26, 277, 1)
INSERT INTO [dbo].[StoreSection] ([StoreSectionID], [Name], [CoordinateX], [CoordinateY], [FloorPlanID]) VALUES (391, N'Kager', 260, 464, 1)
INSERT INTO [dbo].[StoreSection] ([StoreSectionID], [Name], [CoordinateX], [CoordinateY], [FloorPlanID]) VALUES (393, N'Øl', 119, 491, 1)
INSERT INTO [dbo].[StoreSection] ([StoreSectionID], [Name], [CoordinateX], [CoordinateY], [FloorPlanID]) VALUES (394, N'Sodavand', 85, 492, 1)
INSERT INTO [dbo].[StoreSection] ([StoreSectionID], [Name], [CoordinateX], [CoordinateY], [FloorPlanID]) VALUES (395, N'Spiritus', 548, 238, 1)
INSERT INTO [dbo].[StoreSection] ([StoreSectionID], [Name], [CoordinateX], [CoordinateY], [FloorPlanID]) VALUES (396, N'Fransk Vin', 113, 435, 1)
INSERT INTO [dbo].[StoreSection] ([StoreSectionID], [Name], [CoordinateX], [CoordinateY], [FloorPlanID]) VALUES (397, N'Anden vin', 116, 465, 1)
INSERT INTO [dbo].[StoreSection] ([StoreSectionID], [Name], [CoordinateX], [CoordinateY], [FloorPlanID]) VALUES (398, N'Frost1', 192, 348, 1)
INSERT INTO [dbo].[StoreSection] ([StoreSectionID], [Name], [CoordinateX], [CoordinateY], [FloorPlanID]) VALUES (399, N'Kager2', 297, 440, 1)
INSERT INTO [dbo].[StoreSection] ([StoreSectionID], [Name], [CoordinateX], [CoordinateY], [FloorPlanID]) VALUES (400, N'Brød', 220, 458, 1)
INSERT INTO [dbo].[StoreSection] ([StoreSectionID], [Name], [CoordinateX], [CoordinateY], [FloorPlanID]) VALUES (401, N'Frugt', 446, 452, 1)
INSERT INTO [dbo].[StoreSection] ([StoreSectionID], [Name], [CoordinateX], [CoordinateY], [FloorPlanID]) VALUES (402, N'Grønt', 377, 452, 1)
INSERT INTO [dbo].[StoreSection] ([StoreSectionID], [Name], [CoordinateX], [CoordinateY], [FloorPlanID]) VALUES (403, N'Nonfood', 362, 238, 1)
INSERT INTO [dbo].[StoreSection] ([StoreSectionID], [Name], [CoordinateX], [CoordinateY], [FloorPlanID]) VALUES (404, N'Kød1', 221, 249, 1)
INSERT INTO [dbo].[StoreSection] ([StoreSectionID], [Name], [CoordinateX], [CoordinateY], [FloorPlanID]) VALUES (405, N'Kød2', 275, 248, 1)
INSERT INTO [dbo].[StoreSection] ([StoreSectionID], [Name], [CoordinateX], [CoordinateY], [FloorPlanID]) VALUES (406, N'Mel og Sukker', 527, 517, 1)
INSERT INTO [dbo].[StoreSection] ([StoreSectionID], [Name], [CoordinateX], [CoordinateY], [FloorPlanID]) VALUES (407, N'Konserves', 530, 451, 1)
INSERT INTO [dbo].[StoreSection] ([StoreSectionID], [Name], [CoordinateX], [CoordinateY], [FloorPlanID]) VALUES (408, N'Kolonial', 490, 435, 1)
INSERT INTO [dbo].[StoreSection] ([StoreSectionID], [Name], [CoordinateX], [CoordinateY], [FloorPlanID]) VALUES (409, N'Kød3', 303, 248, 1)
INSERT INTO [dbo].[StoreSection] ([StoreSectionID], [Name], [CoordinateX], [CoordinateY], [FloorPlanID]) VALUES (410, N'Andet køl', 26, 330, 1)
INSERT INTO [dbo].[StoreSection] ([StoreSectionID], [Name], [CoordinateX], [CoordinateY], [FloorPlanID]) VALUES (411, N'Peanuts ', 504, 351, 1)
SET IDENTITY_INSERT [dbo].[StoreSection] OFF
