SET IDENTITY_INSERT [dbo].[Item] ON
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (219, N'Brontosaurus XL steak', 791)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (220, N'Frontera', 801)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (221, N'Møllehjul', 792)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (222, N'Butterdejsplader', 792)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (223, N'Miniflutes', 792)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (224, N'Granatæbler', 799)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (225, N'Danske Blomkål', 799)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (226, N'Anne Larsen bageartikler', 794)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (227, N'Fynbo bagefast marmelade', 806)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (228, N'Jakobsens honning', 806)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (229, N'Carletti kæmpeplader', 797)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (230, N'Dr Oetker kagecreme', 797)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (231, N'Dr Oetker KageMousse', 797)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (232, N'Muffinforme', 794)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (233, N'Bageindlæg', 794)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (234, N'Svansø mandler', 799)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (235, N'Amo hvedemel', 809)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (236, N'Flødebolleskaller', 803)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (237, N'Odense Marcipan', 797)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (238, N'Odense Nougat', 797)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (239, N'Pasteurized æg', 810)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (240, N'Bloks Chokolade dragee æg', 797)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (241, N'Sprøjteposer', 794)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (242, N'Dracula Bolcher', 797)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (243, N'Cheasy Skyr', 793)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (244, N'Frilandsæg', 810)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (245, N'Chia kaffe', 811)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (246, N'Quinoa kaffe', 811)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (247, N'Softkernerugbrød', 803)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (248, N'Kanelsnegl', 803)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (249, N'Tebirkes', 803)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (250, N'Meyers rugmel', 809)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (251, N'Meyers brødblanding', 809)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (252, N'Ølands Hvede Mel', 809)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (253, N'Dragsbæk Bagespray', 810)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (254, N'Dragsbæk stegning', 810)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (255, N'Brunchpandekager', 810)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (256, N'Herkules brød', 803)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (257, N'Kohberg Boller', 803)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (258, N'Gårdlykke skinkesalat', 802)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (259, N'Gårdlykke Hønsesalat', 802)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (260, N'Pølsehornspølser', 791)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (261, N'Philadelphia Natural', 802)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (262, N'Philadelphia Grillet paprika', 802)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (263, N'Coop gratineringsost', 793)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (264, N'Gorgonzola', 793)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (265, N'Galbani frisk mozzarella', 793)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (266, N'Laurent Chautemps', 801)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (267, N'Matilde Kakaoskummetmælk', 793)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (268, N'Coca cola', 800)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (269, N'Fanta', 800)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (270, N'Oreo Original', 803)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (271, N'Oreo Golden', 803)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (272, N'Yogi te', 811)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (273, N'Økologisk Sodavand', 800)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (274, N'Karat kaffe', 811)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (275, N'Merrild Special', 811)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (276, N'BKI Extra', 811)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (277, N'Tullamore Dew', 814)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (278, N'BKI Instant', 811)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (279, N'Ærø Øl', 800)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (280, N'Carlsberg Pilsner', 800)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (281, N'Grøn Tuborg', 800)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (282, N'Willemoes øl', 800)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (283, N'Jægermeister', 814)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (284, N'Absolut', 814)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (285, N'Kyllingebrystfillet', 791)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (286, N'Mango Chutney', 806)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (287, N'Egg Noodles', 806)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (288, N'Kims peanuts', 797)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (289, N'365 Økologisk ingefær', 799)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (290, N'Woktern af svinekød', 791)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (291, N'Woktern af oksekød', 791)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (292, N'Singha Beer', 800)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (293, N'Store søde kartofler', 799)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (294, N'Koteletter', 791)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (295, N'Medister', 791)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (296, N'Hakket svinekød', 791)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (297, N'Svinebryst i skiver', 791)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (298, N'Ferske danske kyllingelår', 791)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (299, N'Hakket kylling', 791)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (300, N'Svampe og baconpølser', 791)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (301, N'Pizzadej', 810)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (302, N'Hakket oksekød', 791)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (303, N'Rucolasalat', 799)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (304, N'Hakkede tomater', 795)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (305, N'Pepperoni', 810)
INSERT INTO [dbo].[Item] ([ItemID], [Name], [ItemGroupID]) VALUES (306, N'Skinke strimler', 810)
SET IDENTITY_INSERT [dbo].[Item] OFF
