SET IDENTITY_INSERT [dbo].[ItemGroup] ON
INSERT INTO [dbo].[ItemGroup] ([ItemGroupID], [Name], [ParentItemGroupID]) VALUES (791, N'Kød', NULL)
INSERT INTO [dbo].[ItemGroup] ([ItemGroupID], [Name], [ParentItemGroupID]) VALUES (792, N'Frost', NULL)
INSERT INTO [dbo].[ItemGroup] ([ItemGroupID], [Name], [ParentItemGroupID]) VALUES (793, N'Mejeri', NULL)
INSERT INTO [dbo].[ItemGroup] ([ItemGroupID], [Name], [ParentItemGroupID]) VALUES (794, N'Nonfood', NULL)
INSERT INTO [dbo].[ItemGroup] ([ItemGroupID], [Name], [ParentItemGroupID]) VALUES (795, N'Konserves', NULL)
INSERT INTO [dbo].[ItemGroup] ([ItemGroupID], [Name], [ParentItemGroupID]) VALUES (796, N'Fiske Konserves', 795)
INSERT INTO [dbo].[ItemGroup] ([ItemGroupID], [Name], [ParentItemGroupID]) VALUES (797, N'Konfekture', NULL)
INSERT INTO [dbo].[ItemGroup] ([ItemGroupID], [Name], [ParentItemGroupID]) VALUES (799, N'Frugt og grønt', NULL)
INSERT INTO [dbo].[ItemGroup] ([ItemGroupID], [Name], [ParentItemGroupID]) VALUES (800, N'Øl og vand', NULL)
INSERT INTO [dbo].[ItemGroup] ([ItemGroupID], [Name], [ParentItemGroupID]) VALUES (801, N'Vin', NULL)
INSERT INTO [dbo].[ItemGroup] ([ItemGroupID], [Name], [ParentItemGroupID]) VALUES (802, N'Pålæg', NULL)
INSERT INTO [dbo].[ItemGroup] ([ItemGroupID], [Name], [ParentItemGroupID]) VALUES (803, N'Brød og Kager', NULL)
INSERT INTO [dbo].[ItemGroup] ([ItemGroupID], [Name], [ParentItemGroupID]) VALUES (805, N'Rengøring', NULL)
INSERT INTO [dbo].[ItemGroup] ([ItemGroupID], [Name], [ParentItemGroupID]) VALUES (806, N'Kolonial', NULL)
INSERT INTO [dbo].[ItemGroup] ([ItemGroupID], [Name], [ParentItemGroupID]) VALUES (807, N'Bager', NULL)
INSERT INTO [dbo].[ItemGroup] ([ItemGroupID], [Name], [ParentItemGroupID]) VALUES (808, N'Slagter og Delikatesse', NULL)
INSERT INTO [dbo].[ItemGroup] ([ItemGroupID], [Name], [ParentItemGroupID]) VALUES (809, N'Mel og Sukker', 806)
INSERT INTO [dbo].[ItemGroup] ([ItemGroupID], [Name], [ParentItemGroupID]) VALUES (810, N'Kølevarer', NULL)
INSERT INTO [dbo].[ItemGroup] ([ItemGroupID], [Name], [ParentItemGroupID]) VALUES (811, N'Kaffe og Te', NULL)
INSERT INTO [dbo].[ItemGroup] ([ItemGroupID], [Name], [ParentItemGroupID]) VALUES (812, N'Saft og Juice', NULL)
INSERT INTO [dbo].[ItemGroup] ([ItemGroupID], [Name], [ParentItemGroupID]) VALUES (813, N'Rynkeby kids', 812)
INSERT INTO [dbo].[ItemGroup] ([ItemGroupID], [Name], [ParentItemGroupID]) VALUES (814, N'Spiritus', NULL)
INSERT INTO [dbo].[ItemGroup] ([ItemGroupID], [Name], [ParentItemGroupID]) VALUES (815, N'Personlig pleje', NULL)
SET IDENTITY_INSERT [dbo].[ItemGroup] OFF
